version: '3'

services:
  web:
    environment:
      AppSettings__AdminEmail: "admin@email.com"
      AppSettings__AdminPassword: "P@ssw3rd!"
      ConnectionStrings__Redis: "redis:6379"
      ConnectionStrings__RolleiShop: "Server=postgres;Port=5432;Database=RolleiShop;User ID=postgres;Password=P@ssw0rd!;"
      ConnectionStrings__Identity: "Server=postgres;Port=5432;Database=RolleiShopIdentity;User ID=postgres;Password=P@ssw0rd!;"
      ApplicationSettings__RedisInstanceName: "rolleishop"

  postgres:
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd!"

  nginx:
    ports:
      - "80:80"
