version: '3'

services:
  web:
    build: ./src/RolleiShop
    restart: always
    volumes:
      - static:/app/wwwroot/
    networks:
      - web_nw
      - db_nw
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://*:5000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_nw

  redis:
    image: redis
    restart: always
    networks:
      - db_nw

  nginx:
    build: ./src/Nginx
    restart: always
    volumes:
      - static:/app/wwwroot/
    networks:
      - web_nw
    depends_on:
      - web

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
   db:
   static:
